language: python
sude: false
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.7.1
matrix:
  exclude:
    - python: 3.4
      env: DJANGO_VERSION=1.6.8
install:
  - pip install .
  - pip install -r dev-requirements.txt
  - pip install Django==$DJANGO_VERSION coveralls
script:
  - ./create_coverage.sh
after_success:
  - coveralls